name: diplodatos-datacuration
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - seaborn=0.11
  - missingno
  - scikit-learn
  - nltk
  - geopandas
  - requests